### ISSUE TITLE
Can't use kriber on specific environment

### ISSUE THREAD

**Issue by andreeleuterio** [stefsmeets/focus_package#3]
Hi,
I am trying to run kriber/dls76 on a Linux cluster, without root permissions, with python 2.7.7 installed on a non-default location. I get the following error:

```
Traceback (most recent call last):
  File "/home/tmp/path/to/focus-py/bin/kriber", line 9, in <module>
    load_entry_point('focus-package==1.1', 'console_scripts', 'kriber')()
  File "/home/tmp/path/to/focus-py/lib/python2.7/site-packages/focus_package-1.1-py2.7.egg/focus_tools/pykriber.py", line 143, in kriber_entry
    kriber(args=fns)
  File "/home/tmp/path/to/focus-py/lib/python2.7/site-packages/focus_package-1.1-py2.7.egg/focus_tools/pykriber.py", line 132, in kriber
    sp.call([kriber_exe] + args)
  File "/path/to/python/2.7.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/path/to/python/2.7.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/path/to/python/2.7.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

How can I get around that?
Thank you in advance,
Andre

**Comment by andreeleuterio** [comment]
UPDATE:

I was able to fix the previous issue with chmod +x on
/pathtofocus/lib//python2.7/site-packages/focus_package-1.1-py2.7.egg/bin/*

But now when running kriber I am not prompted whether to enter TETCON lines or not. 
I remember when working on the FOCUS package without python wrappers that the kriber.c code had the printfs for the option "DLSinput with TETCON cards? (y/n): => " commented out, and the default option was no. I can't find the file; I assumed it's precompiled. How can we check that; or maybe I'm missing something?

**Comment by stefsmeets** [comment]
@aeleuterio: If I remember correctly I changed this a while ago, so that I could automate writing DLS files. You can write TETCON cards via the `writc` command. The `wriid` command writes DLS input files without TETCON cards.

**Comment by andreeleuterio** [comment]
@stefsmeets Thank you for your prompt reply.
I have the attached a dlsinp file that has been previously tested on a different version of the focus package. My dls76.out file has the following lines:

```
0*** WARNING: ATOM TYPE ^G^@^@ PUNCHED ON BONDIS CARD NO  1 DOES NOT APPEAR ON AN ATOM CARD
0*** WARNING: ATOM TYPE ¦^AJ PUNCHED ON BONDIS CARD NO  1 DOES NOT APPEAR ON AN ATOM CARD
0*** WARNING: ATOM TYPE ^@^@^@ PUNCHED ON BONDIS CARD NO  1 DOES NOT APPEAR ON AN ATOM CARD
0*** ERROR: NO DISTANCE FUNCTION SUPPLIED FOR BOND TYPE T   - O   - T
             SPECIFIED ON TETCON CARD NO  1 (T1    - O1    ... T8     BOND)
```

The error then shows up several times until the end of the file where it says

```
0THERE ARE AT LEAST  38 FATAL ERRORS IN THIS INPUT. EXECUTION IS TERMINATED
0*** FINISH ***
```

It looks like atom type T is being read as `^G^@^@`, atom type O is being read as `¦^AJ` and the second type T as `^@^@^@`.

I would appreciate any support - if you'd prefer to discuss this over email rather than this thread please let me know.
Thank you again,
Andre

**Comment by stefsmeets** [comment]
@aeleuterio This looks like an encoding problem, maybe in the way you save your strudat file. If you want me to have a look, you can send your strudat / dlsinp to me.
